import Header from "@/components/Header/Header";
import SideNav from "@/components/SideNav/SideNav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import AuthSessionProvider from "@/providers/session-provider";
import Providers from "@/utils/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <Providers>
          <AuthSessionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <div className="flex min-h-full flex-col">
                <Header />

                <div className="mx-auto flex w-full max-w-full items-start gap-x-8 px-2 py-10 sm:px-6 lg:px-8 h-full">
                  <aside className="sticky top-8 hidden w-80 shrink-0 lg:block h-full">
                    <SideNav />
                  </aside>

                  {children}
                </div>
              </div>
            </ThemeProvider>
          </AuthSessionProvider>
        </Providers>
      </body>
    </html>
  );
}
